import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZonelessChangeDetection,importProvidersFrom } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { routes } from './app.routes';
import { jwtInterceptor } from './interceptors/jwt-interceptor';
import { LucideAngularModule,Book,
  Home,
  LayoutDashboard,
  Grid,
  List,
  ClipboardList,
  Shield,
  ShieldCheck,
  Users,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  Settings,
  Sliders,
  BarChart,
  PieChart,
  LineChart,
  Activity,
  Mail,
  Inbox,
  Send,
  FileText,
  Folder,
  FolderPlus,
  Calendar,
  Clock,
  Bell,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  Truck,
  Package,
  Box,
  Columns,
  Table,
  FilePlus,
  Plus,
  Minus,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Lock,
  Unlock,
  LogOut,
  LogIn,
  Menu,             // pour fallback
  Circle} from 'lucide-angular';
import { tokenExpirationInterceptor } from './interceptors/tokenexpiration';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withInterceptors([jwtInterceptor])),
    provideHttpClient(
      withInterceptors([tokenExpirationInterceptor])
    ),
    importProvidersFrom(
      LucideAngularModule.pick({ Package, Users,LayoutDashboard,ShieldCheck,Book,Menu,
  Home,
  Grid,
  List,
  ClipboardList,
  Shield,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  Settings,
  Sliders,
  BarChart,
  PieChart,
  LineChart,
  Activity,
  Mail,
  Inbox,
  Send,
  FileText,
  Folder,
  FolderPlus,
  Calendar,
  Clock,
  Bell,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  Truck,
  Box,
  Columns,
  Table,
  FilePlus,
  Plus,
  Minus,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Lock,
  Unlock,
  LogOut,
  LogIn,             // pour fallback
  Circle}) 
    )
  ]
};